# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZTget4AU1khLVJ1bDg1yCGMbXXm3Own
"""

import pandas as pd
data=pd.read_csv("/content/Salary_Data.csv")
# data.isnull().sum()

"""First, let's separate numerical and categorical columns to apply appropriate imputation methods. Numerical columns will be filled with the mean, and categorical columns with the mode."""

# Identify numerical and categorical columns
numerical_cols = data.select_dtypes(include=['number']).columns
categorical_cols = data.select_dtypes(include=['object']).columns

print("Numerical columns:", numerical_cols.tolist())
print("Categorical columns:", categorical_cols.tolist())

"""Now, let's fill the null values. Numerical columns will be imputed with the mean, and categorical columns with the mode."""



# Impute numerical columns with the mean
for col in numerical_cols:
    if data[col].isnull().any():
        data[col].fillna(data[col].mean(), inplace=True)

# Impute categorical columns with the mode
for col in categorical_cols:
    if data[col].isnull().any():
        # Use .iloc[0] because mode() can return multiple values if there's a tie
        data[col].fillna(data[col].mode()[0], inplace=True)

print("Null values after imputation:")
display(data.isnull().sum())

from sklearn.preprocessing import LabelEncoder



"""Now, let's remove any duplicate rows from the dataset to ensure data uniqueness."""

print(f"Shape of data before removing duplicates: {data.shape}")
data.drop_duplicates(inplace=True)
print(f"Shape of data after removing duplicates: {data.shape}")

from sklearn.preprocessing import LabelEncoder

"""Now, let's encode the categorical columns using `LabelEncoder`."""

from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Apply LabelEncoder to categorical columns
for col in categorical_cols:
    data[col] = label_encoder.fit_transform(data[col])

print("DataFrame after Label Encoding:")
display(data.head())

"""Now, let's prepare the data for machine learning by splitting it into training and testing sets. We will use 'Salary' as our target variable (y) and the remaining columns as features (X)."""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Make a copy of the DataFrame to ensure encoding changes don't affect previous cells if re-run out of order
data_encoded = data.copy()

# Apply LabelEncoder to categorical columns directly before splitting
# This ensures X and y are always numeric at this point
for col in categorical_cols:
    if data_encoded[col].dtype == 'object':
        label_encoder = LabelEncoder()
        data_encoded[col] = label_encoder.fit_transform(data_encoded[col])

# Define features (X) and target (y)
X = data_encoded.drop('Salary', axis=1)
y = data_encoded['Salary']

# Perform the train-test split (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

"""First, let's import the necessary libraries for our models and evaluation metrics."""

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR # Import Support Vector Regressor
from sklearn.neighbors import KNeighborsRegressor # Import K-Nearest Neighbors Regressor
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

"""### Linear Regression

We'll start by training a simple Linear Regression model.
"""

# Initialize and train the Linear Regression model
linear_reg = LinearRegression()
linear_reg.fit(X_train, y_train)

# Make predictions
y_pred_lr = linear_reg.predict(X_test)

# Evaluate the model
mse_lr = mean_squared_error(y_test, y_pred_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print(f"Linear Regression - Mean Squared Error: {mse_lr:.2f}")
print(f"Linear Regression - R2 Score: {r2_lr:.2f}")

"""### Decision Tree Regressor

Next, let's train a Decision Tree Regressor.
"""

# Initialize and train the Decision Tree Regressor model
decision_tree_reg = DecisionTreeRegressor(random_state=42)
decision_tree_reg.fit(X_train, y_train)

# Make predictions
y_pred_dt = decision_tree_reg.predict(X_test)

# Evaluate the model
mse_dt = mean_squared_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print(f"Decision Tree Regressor - Mean Squared Error: {mse_dt:.2f}")
print(f"Decision Tree Regressor - R2 Score: {r2_dt:.2f}")

"""### Random Forest Regressor

Finally, we'll train a Random Forest Regressor, which is an ensemble method often providing better performance.
"""

# Initialize and train the Random Forest Regressor model
random_forest_reg = RandomForestRegressor(random_state=42)
random_forest_reg.fit(X_train, y_train)

# Make predictions
y_pred_rf = random_forest_reg.predict(X_test)

# Evaluate the model
mse_rf = mean_squared_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print(f"Random Forest Regressor - Mean Squared Error: {mse_rf:.2f}")
print(f"Random Forest Regressor - R2 Score: {r2_rf:.2f}")

"""### Support Vector Regressor (SVR)

Let's evaluate the performance of an SVR model.
"""

# Initialize and train the SVR model
svr_reg = SVR()
svr_reg.fit(X_train, y_train)

# Make predictions
y_pred_svr = svr_reg.predict(X_test)

# Evaluate the model
mse_svr = mean_squared_error(y_test, y_pred_svr)
r2_svr = r2_score(y_test, y_pred_svr)

print(f"SVR - Mean Squared Error: {mse_svr:.2f}")
print(f"SVR - R2 Score: {r2_svr:.2f}")

"""### K-Nearest Neighbors Regressor

Finally, let's train a K-Nearest Neighbors Regressor.
"""

# Initialize and train the KNN model
knn_reg = KNeighborsRegressor()
knn_reg.fit(X_train, y_train)

# Make predictions
y_pred_knn = knn_reg.predict(X_test)

# Evaluate the model
mse_knn = mean_squared_error(y_test, y_pred_knn)
r2_knn = r2_score(y_test, y_pred_knn)

print(f"KNN - Mean Squared Error: {mse_knn:.2f}")
print(f"KNN - R2 Score: {r2_knn:.2f}")

"""## Model Comparison

Let's compare the performance of all trained models.
"""

results = {
    'Model': ['Linear Regression', 'Decision Tree', 'Random Forest', 'SVR', 'KNN'],
    'Mean Squared Error': [mse_lr, mse_dt, mse_rf, mse_svr, mse_knn],
    'R2 Score': [r2_lr, r2_dt, r2_rf, r2_svr, r2_knn]
}

results_df = pd.DataFrame(results)
display(results_df.sort_values(by='R2 Score', ascending=False))

"""### Visual Comparison of Model Performance"""

import matplotlib.pyplot as plt
import seaborn as sns

# Sort for better visualization
results_df_sorted_r2 = results_df.sort_values(by='R2 Score', ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x='Model', y='R2 Score', data=results_df_sorted_r2, palette='viridis')
plt.title('R2 Score Comparison of Regression Models')
plt.ylabel('R2 Score')
plt.xlabel('Model')
plt.xticks(rotation=45)
plt.ylim(results_df_sorted_r2['R2 Score'].min() - 0.1, 1) # Adjust y-axis limit for better visibility
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Sort for better visualization (lower MSE is better)
results_df_sorted_mse = results_df.sort_values(by='Mean Squared Error', ascending=True)

plt.figure(figsize=(10, 6))
sns.barplot(x='Model', y='Mean Squared Error', data=results_df_sorted_mse, palette='magma')
plt.title('Mean Squared Error (MSE) Comparison of Regression Models')
plt.ylabel('Mean Squared Error')
plt.xlabel('Model')
plt.xticks(rotation=45)
plt.yscale('log') # Use a log scale for MSE due to large differences
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""## Save the Best Model"""

import pickle

# The Random Forest Regressor was identified as the best model
best_model = random_forest_reg

# Define the filename for the saved model
model_filename = 'random_forest_regressor_model.pkl'

# Save the model to a .pkl file
with open(model_filename, 'wb') as file:
    pickle.dump(best_model, file)

print(f"Best model (Random Forest Regressor) saved to {model_filename}")

"""You can load the saved model later using:
```python
with open('random_forest_regressor_model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)
# Now you can use loaded_model for predictions
```

## Generate `app.py` file

This `app.py` script demonstrates how to load the previously saved `random_forest_regressor_model.pkl` and use it to predict salaries for new input data. The script assumes that categorical features in the input (Gender, Education Level, Job Title) are already numerically encoded using the same mapping as during model training.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import pickle
# import pandas as pd
# import numpy as np
# 
# # Load the trained model
# try:
#     with open('random_forest_regressor_model.pkl', 'rb') as file:
#         model = pickle.load(file)
#     print("Model loaded successfully.")
# except FileNotFoundError:
#     print("Error: 'random_forest_regressor_model.pkl' not found. Please ensure the model is saved.")
#     exit()
# 
# def predict_salary(age, gender, education_level, job_title, years_of_experience):
#     """
#     Predicts salary using the loaded Random Forest Regressor model.
# 
#     Args:
#         age (float): Age of the individual.
#         gender (int): Encoded gender (e.g., 0 for Female, 1 for Male).
#         education_level (int): Encoded education level (e.g., 0 for Bachelor's, 1 for Master's, etc.).
#         job_title (int): Encoded job title.
#         years_of_experience (float): Years of experience.
# 
#     Returns:
#         float: Predicted salary.
#     """
#     # Create a DataFrame from the input features
#     input_data = pd.DataFrame([[age, gender, education_level, job_title, years_of_experience]],
#                               columns=['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience'])
# 
#     # Make prediction
#     prediction = model.predict(input_data)[0]
#     return prediction
# 
# if __name__ == "__main__":
#     print("\n--- Salary Prediction Example ---")
# 
#     # Example 1: Predict salary for a sample individual
#     # NOTE: 'Gender', 'Education Level', and 'Job Title' must be numerically encoded
#     # according to the LabelEncoder fitted during training. For a real application,
#     # you would need to store and re-use the fitted LabelEncoders or create a mapping.
#     sample_age = 30.0
#     sample_gender = 1 # Assuming 1 for Male, 0 for Female based on training data's encoding
#     sample_education_level = 0 # Assuming 0 for a specific education level based on training data's encoding
#     sample_job_title = 50 # Assuming 50 for a specific job title based on training data's encoding
#     sample_years_of_experience = 5.0
# 
#     predicted_salary = predict_salary(
#         sample_age,
#         sample_gender,
#         sample_education_level,
#         sample_job_title,
#         sample_years_of_experience
#     )
# 
#     print(f"Input features: Age={sample_age}, Gender={sample_gender}, "
#           f"Education Level={sample_education_level}, Job Title={sample_job_title}, "
#           f"Years of Experience={sample_years_of_experience}")
#     print(f"Predicted Salary: ${predicted_salary:,.2f}")
# 
#     # Example 2: Another prediction
#     sample_age_2 = 45.0
#     sample_gender_2 = 0 # Female
#     sample_education_level_2 = 3 # Another education level
#     sample_job_title_2 = 120 # Another job title
#     sample_years_of_experience_2 = 15.0
# 
#     predicted_salary_2 = predict_salary(
#         sample_age_2,
#         sample_gender_2,
#         sample_education_level_2,
#         sample_job_title_2,
#         sample_years_of_experience_2
#     )
#     print(f"\nInput features: Age={sample_age_2}, Gender={sample_gender_2}, "
#           f"Education Level={sample_education_level_2}, Job Title={sample_job_title_2}, "
#           f"Years of Experience={sample_years_of_experience_2}")
#     print(f"Predicted Salary: ${predicted_salary_2:,.2f}")